### ISSUE TITLE
/api requires authentication

### ISSUE THREAD

**Issue by blake1029384756** [grocy/grocy#1216]
I am using 'ReverseProxyAuthMiddleware' for authentication. I set my auth provider to bypass authentication on the /api endpoint so grocy-android can access it as suggested [here](https://github.com/patzly/grocy-android/issues/255). 

This results in an "invalid username" when accessing the api
`array(0) {
}
{"error_message":"ReverseProxyAuthMiddleware: Invalid username from proxy: ","error_details":{"stack_trace":"#0 \/app\/grocy\/middleware\/AuthMiddleware.php(52): Grocy\\Middleware\\ReverseProxyAuthMiddleware->authenticate(Object(Slim\\Http\\ServerRequest))\n#1 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke(Object(Slim\\Http\\ServerRequest), Object(class@anonymous))\n#2 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\\Http\\ServerRequest))\n#3 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process(Object(Slim\\Http\\ServerRequest), Object(class@anonymous))\n#4 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\\Http\\ServerRequest))\n#5 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process(Object(Slim\\Http\\ServerRequest), Object(class@anonymous))\n#6 \/app\/grocy\/middleware\/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\\Http\\ServerRequest))\n#7 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke(Object(Slim\\Http\\ServerRequest), Object(class@anonymous))\n#8 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\Http\\ServerRequest))\n#9 \/app\/grocy\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle(Object(Slim\\Http\\ServerRequest))\n#10 \/app\/grocy\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle(Object(Slim\\Http\\ServerRequest))\n#11 \/app\/grocy\/app.php(77): Slim\\App->run()\n#12 \/app\/grocy\/public\/index.php(45): require_once('\/app\/grocy\/app....')\n#13 {main}","file":"\/app\/grocy\/middleware\/ReverseProxyAuthMiddleware.php","line":25}}`

**Comment by berrnd** [comment]
When `ReverseProxyAuthMiddleware` is used, _everything_ is supposed to be authenticated via your reverse proxy, there is no exception for the API.

However, I've added that _additionally_ a valid API key is also ok for `ReverseProxyAuthMiddleware` - so what you thought of should now work.

**Comment by carldavis** [comment]
I still get a similar error when using barcode buddy to redirect into grocy to add a product. If I have 

`        location /api {
                include /config/nginx/proxy.conf;
                proxy_pass http://grocy;
`

to bypass Authelia I get the error, If I drop that section it works fine. (barcode buddy and grocy are containerized so barcodebuddy is bypassing my swag-authelia instance completely)

**Comment by berrnd** [comment]
Double check that a valid API key is used.

However, if you want to have groxcy authenticated via Authelia and it works also for the API, I don't really understand why an exception for the API is better...

(And that's not the best place this, if you have a reproducible problem, please open a new issue with everything needed to reproduce it, if it's more a help request, please use the subreddit as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).)

**Comment by vctls** [comment]
What is the recommended way of handling both SSO through an authenticating proxy like Authelia for the web app, and API key authentication for the mobile app?
I managed to get both working with nginx and Authelia by doing something like this, but I'm not sure that's recommended…
```
location ~* /api/? {
    proxy_pass http://grocy:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    if ($http_grocy_api_key = "") {
       rewrite ^/api/(.*)$ /_api/$1 last;
    }
}

location ~* /_api/? {
    rewrite ^/_api/(.*)$ /api/$1 break;
    include /config/nginx/snippets/authelia-authrequest.conf;
    proxy_pass http://grocy:80;
    internal;
}
```
