### ISSUE TITLE
Bug: Unable to run grocy: PHP module 'intl' not installed, but required.

### ISSUE THREAD

**Issue by bob5731** [grocy/grocy#1764]
I get Unable to run grocy: PHP module 'intl' not installed, but required.

I used the https://peppe8o.com/manage-your-home-stocks-like-a-pro-with-grocy-and-raspberry-pi/
I'm suing a raspberry-pi 3 b+
I can get it ot work. how do I fix it?

**Comment by Bontah** [comment]
i'll assume you're running php 7.4 if you followed that guide you provided.

install the intl module with
`sudo apt install php7.4-intl`
and restart your apache2 webserver
`sudo systemctl restart apache2.service`

it should now work or show another error if something else is missing

**Comment by berrnd** [comment]
> I get Unable to run grocy: PHP module 'intl' not installed, but required.

The error message named it: Install the `intl` extension. 🙄

This is the place for reproducible issues. The better place for general help / usage questions is the r/grocy subreddit. All that is [mentioned in README](https://www.reddit.com/r/grocy) and on the issue template, which you obviously ignored both.

**Comment by bob5731** [comment]
sudo apt install php7.4-intl
and restart your apache2 webserver
sudo systemctl restart apache2.service
did not work.

**Comment by bob5731** [comment]
what barcode screener work with grocy

**Comment by berrnd** [comment]
> what barcode screener work with grocy?

It's still not the right place for help questions here.

A barcode scanner is technically a keyboard. So any one will work.
