### ISSUE TITLE
Feature Request: Support for External RDBMS

### ISSUE THREAD

**Issue by jnix85** [grocy/grocy#2582]
Hello,

First, I want to express my appreciation for your work on Grocy! It’s been a fantastic tool, and I truly enjoy using it.

I would like to request the addition of support for using an external RDBMS (e.g., MySQL, PostgreSQL). Currently, Grocy only supports SQLite, which is great for lightweight and simple setups. However, for some users, including myself, using an external RDBMS could provide significant advantages, especially for backup and recovery purposes. External RDBMS options offer more robust solutions for data integrity, scalability, and administrative tools that are better suited for complex environments.

### **Use Case:**

- Ensuring smoother backup and recovery processes, particularly in cases where frequent or automated backups are necessary.
- Enhancing data management capabilities and scalability as data grows, or in more demanding multi-user environments.
- Offering better options for high availability and redundancy, features that external databases provide.

I understand this may involve a non-trivial amount of development work, but I believe this could be a valuable feature for users who want to leverage more robust database management systems.

### **Benefits:**

1. Improved Data Backup & Recovery: An external RDBMS can streamline backup and recovery workflows by using native database tools.
2. Better Data Integrity & Scalability: External RDBMS options, such as MySQL or PostgreSQL, offer more features to handle growing datasets.
3. Compatibility with Enterprise Environments: Some users may prefer or require RDBMS solutions for compliance or organizational policy reasons.

### **Conclusion:**

I’d love to hear your thoughts on whether support for an external RDBMS might be possible in the future, and I’m happy to provide any feedback or testing if needed.

Thank you for your consideration, and again, thank you for all your hard work on Grocy!

Best Regards,
Jason Parks

**Comment by berrnd** [comment]
Please be so kind and do a little tiny search before opening new requests: Duplicate of #89 (and #1071).

&nbsp;
> External RDBMS options offer more robust solutions for data integrity, scalability, and administrative tools that are better suited for complex environments.

Reality check: Is your home a 10k+ users highly sensitive business environment? Then Grocy doesn't fit your home and that's just fine.

Using SQLite exclusively was a design decision which won't be changed. And it perfectly fits the target use case (again: a home, not a business) more than fine, since years and counting.

Btw: The official demo instances are also not a common home use case environment, but serve daily more page views than any common private instance will see in more than a month - also without any issues and with little resources at warp speed ([reference](https://www.reddit.com/r/grocy/comments/15lm1he)). If you have performance issues, that's most of the time just a badly configured web server and unrelated to the RDBMS choice.

**Comment by berrnd** [comment]
> both of those requests have their comments section locked

True for #89, not true for #1071. The decision for this project has been made years ago. Accept it or simply create your own so much better solution. Don't get the point on discussing an already decided thing endlessly, that's simply the reason on locking threads just like always.

&nbsp;
> For me, it's about backups

As said, I host beside my personal instance most probably the biggest one on planet earth, the official demo instances. Backing up a file is as easy as backing up a file. Never ever had a problem here or on any other software using SQLite targeting my home environment. Do you?

&nbsp;
> SQLite doesn't really lend itself to automated backups or restorations, beyond backing up the full file.

We talk about kilobytes initially and this maybes go up a few megabytes after years of really using Grocy. Last time I thought about if backing up 30 MB is a problem was probably 1996.

&nbsp;
> The other main use case for an external db for me is the ability to easily query the data.

Also don't get that point. Querying a SQLite DB is probably much more easy than any server based RDBMS, since simply no server is needed. Sounds for me just once more that your very personal comfort zone is out of SQLite. Fixing personal "problems" (on learning new stuff) is also out of scope of this project.

&nbsp;

> it'd be nice to directly manipulate the data

Very wrong approach in general, however already possible - it's SQLite, the probably most easy yet lightweight RDBMS out there. Just like with any application [the API](https://demo-prerelease.grocy.info/api) is the way to go. Doing stuff "from the backside" lead to bullshit more than once. Expect to be blamed by me if ever posting help on such a thing here.

&nbsp;
Btw: Not a single one of the as of today [455 solved issues](https://github.com/grocy/grocy/issues?q=is%3Aissue+is%3Aclosed+label%3Abug) were caused by the RDBMS choice. Don't fear, step out your comfort zone and simply use stuff practically and don't overthink the theory.

**Comment by travisterrell** [comment]
Thanks for your well thought out response. I'll chew on this a bit. Agree about not manipulating data manually; that's a thing I've been battling with some users in a v2.0 of a product. The data became a mess in the old one, so on the new version one I've repeatedly found myself saying, "Just tell me the use cases I'll add endpoints to handle it!" (More for modifying; they can select all they want.) Anyway, I would definitely not be complaining about problems resulting for that non-supported scenario, haha. 

Of note for my non-typical use case, I've generated barcode stickers and abused grocy to inventory a **lot** of non-grocery belongings (particularly things in storage, in the attic, etc.) There are some alternative platforms I've tried, as obviously grocy isn't built for it, but nothing else has been significantly better enough to switch, so it's where I am _for today._ I have toyed with building something simple from scratch—and that's probably the _best_ path, since it's a custom use and I don't even need many features beyond quick entry with barcodes. Just... time. Haha.

Thanks again.

**Comment by berrnd** [comment]
> Of note for my non-typical use case [...]

Grocy is from the ground up meant to be a very open system, not enforcing a specific workflow just like anywhere. So it's more than fine to abuse it for whatever you want, have fun on whatever it makes it useful for personally you. However, we're here for SQLite part: So have you had any Grocy issues so far and if, can any of them really be caused by SQLite? I doubt it.

&nbsp;
> I'm a fan

Being a fan is one thing, parts of what you describe sound more like you only know / want to use that / what you know then instead of something else, even though that something else fits the corresponding use case so much better. Grocy is not doing time series stuff in any way.

&nbsp;
> Yes, but in a use case that was (imho) inappropriate for sqlite from the start.

Well, comparing apples with pears. Rethink the use case of Grocy, be it yours or the designed one (managing a home, not having many users; not having many concurrent access; making it easy to install with as few dependencies as possible) and then re-decide once more if SQLite isn't the best fit here. You essentially said "I abused SQLite once af, it worked badly (what a surprise) and now it's supposed to work as badly for any other use case too, because it's SQLite". That SQLite fear is real my dear and for whatever reason you're not alone, all the related threads here turn out to be self-help group for all such patients. Lol.

But no worries, @pgy866 (in https://github.com/grocy/grocy/issues/89#issuecomment-1034808993), @NikoGrano (in https://github.com/grocy/grocy/issues/89#issuecomment-565813436) and @hackathi (in https://github.com/grocy/grocy/pull/1510#issuecomment-869063449) (just to quote a few) already made very big and loud announcements years ago to help out humanity on making the so much better Grocy in any way. Well, very loud in theory, but not a single bit happened in reality since then. At the same time thousands of other users enjoy Grocy how it is, having no single RDBMS (or anything else being only a theoretical problem) related issue. [Badumtss](https://www.youtube.com/watch?v=6zXDo4dL7SU).

&nbsp;
So simply come back once you really have a practical problem with Grocy which is entirely caused by my RDBMS choice, looking forward to that day.

**Comment by hackathi** [comment]
> But no worries, @pgy866 (in https://github.com/grocy/grocy/issues/89#issuecomment-1034808993), @NikoGrano (in https://github.com/grocy/grocy/issues/89#issuecomment-565813436) and @hackathi (in https://github.com/grocy/grocy/pull/1510#issuecomment-869063449) (just to quote a few) already made very big and loud announcements years ago to help out humanity on making the so much better Grocy in any way. Well, very loud in theory, but not a single bit happened in reality since then. At the same time thousands of other users enjoy Grocy how it is, having no single RDBMS (or anything else being only a theoretical problem) related issue. [Badumtss](https://www.youtube.com/watch?v=6zXDo4dL7SU).

I really don't know how I offended you so deeply that you need to publicly shame me, despite knowing nothing about what I have done since deciding to roll my own software.

But if you must, I'll educate you: I've since scrapped the whole codebase, because it is riddled with rounding errors, that, funnily enough, stem from a complete lack of understanding how type coalescing between sqlite and php works, which results in absurd rouding errors all over the place that are half-assedly fixed in the UI layer, but polluting the data everywhere.

Also: my rewrite is up and running, but with no intentions of open sourcing it. So please, leave me out of your drama and maybe, just maybe, listen to some people. Knowledge might stick, I know it's scary.

**Comment by travisterrell** [comment]
I appreciate the effort you put into replying here, but from the points you made, I feel like you may have misinterpreted my anecdotes about other products as further arguments for Grocy to adopt a traditional RDBMS. In the first paragraph I tried to suggest that I was going to try to take your comments in stride and to experiment more about SQLite, but I probably could've been more explicit. But I also tried to use "for my use case" a lot, particularly in the first one wherein I was trying to acknowledge that SQLite may be a reasonable choice overall, just that I suspected there might be something more appropriate to fit my specific wishes. Definitely wasn't asking you to switch to it or provide support for any weird thing I do on my own. :)

So yeah, I wasn't trying to provide any feedback about using SQLite for _Grocy_ in the message you replied to, but I do want to clarify one relevant area where I felt a little misquoted:
> > I'm a fan
> 
> Being a fan is one thing, parts of what you describe sound more like you only know / want to use that / what you know then instead of something else, even though that something else fits the corresponding use case so much better. Grocy is not doing time series stuff in any way.

Your quote excludes the crucial 2nd half of that sentence. '(I'm a fan, so just sharing **in case you ever have the need to store lots of time-series data**.)' This was in response to your question about whether I'd ever had an issue with SQLite in the past "here or **on any other software** using SQLite **targeting my home environment**" Was just answering that question! Haha. I agree 100% about choosing technologies that match the use case, even if one must consider new-to-them technologies. This is actually a perfect example of that: PostgreSQL and TimescaleDB were both brand new to me. I chose them specifically because they were a better option for the described use case. Sorry, just sharing what I thought was a nifty piece of technology, while acknowledging that the use case is different than Grocy's.

>   So simply come back once you really have a practical problem with Grocy which is entirely caused by my RDBMS choice, looking forward to that day.

No need for defensiveness, ha! Though I understand that you've had to argue for it a lot in the past so are possibly primed for it—especially as this software seems to attract a fair number of issues from less-technical users. Just to be extra clear—I didn't post the original issue, nor ask for help in my responses (I even said "don't feel compelled to respond.") Maybe I just suck at it, but I did made an explicit effort to shape my replies so they didn't sound like complaints or requests, and made sure to thank you for your development efforts in each of them, as the software has been quite helpful to me! 

Well, in any case, thanks again for your work on this project.

**Comment by berrnd** [comment]
> I've since scrapped the whole codebase, because it is riddled with rounding errors [...]

3 years later and it's still the same - just what you most likely wanted to say quickly summed up using some more clear words: "You are dumb as fuck and only I know how to do it right". Thanks again, I know I'm dumb af, and a asshole, of course in any single aspect of life.

&nbsp;
> Also: my rewrite is up and running

Plottwist: I also have a so much better Grocy running at home, using a proper RDBMS and of course with all the other stuff you love too. Doubt it? Prove me wrong. Of course I also don't have the intention to open source that. Still so loud, yet quiet. For me it's still a mystery, how such a from the ground up so bad software like Grocy can help / be enjoyed by so much people since years. If you'd have the balls, simply publish your so much better code so that I and anyone else on this planet can blame every single line of it in the same way you still do it here. If some of my general design ideas (not specifically bad code related) were on there, I could probably never stop laughing again.

&nbsp;
> So please, leave me out of your drama

Using big and not so nice words years ago publicly can maybe follow you years later, since the internet vergisst nix (obviously), I know it's scary.

&nbsp;
> in a modern containerized environment
> file access for a can be quite a bit more difficult
> particularly when the connecting client is on a different physical machine

Also have all that in place for any Grocy instance I host publicly and privately. Don't have any of those problems. All that is software, endless possibilities, you just need to utilize them. If such a setup is above one's skills, I'd just do it the more classic, probably more easy way.

&nbsp;
> popular database clients

Just again the same: Step out of your personal comfort zone and use whatever fits the particular use case best. There are very [great graphical tools](https://sqlitebrowser.org/) out there, if the graphical approach is the required way for you. A general purpose tool probalby only fits a general purpose and at least for me that's not that much a surprise.

&nbsp;
> don't feel compelled to respond

I'm sure you've read a lot of the other threads about that beforehand so you know how I respond to stuff. So chiming in into a random thread from someone else sounds for me like you looked exactly for such a reaction - and of course I'm here to fulfill that.

**Comment by hackathi** [comment]
> Using big and not so nice words years ago publicly can maybe follow you years later, since the internet vergisst nix (obviously), I know it's scary.

Please point out exactly where I went "not so nice" years ago. In the mean time, the next time I'll be sucked into your drama, my lawyer will be in touch.

**Comment by berrnd** [comment]
> my lawyer will be in touch

Me too.

Since it seems to be all about education here: Thinking thoroughly what to write where, especially when doing it publicly, would be just another crazy approach.

In the mean time, I'll close this Kindergarten (even it's pure entertainment) for now, see in you in 3 years, but not-grocy.
