### ISSUE TITLE
Remove amount value decimal digit restriction / improve input validation

### ISSUE THREAD

**Issue by fusion44** [grocy/grocy#998]
Hi!

I have a salad, where the receipt is denominated in kg. A recent recent purchase is 0.186 kg for 1.53 € in total (8.20 € / kg) according to the receipt. The buy and storage unit of the Grocy product can be grams or kg (I've tried both).

There are problems with using grams or kg as unit of purchase / storage:

**gram:**
I can enter the purchased amount as 186 g, but the purchase price will be displayed as 0.008€ for each gram. The value is rounded and when I recalculate the original price from the displayed values, the result will differ by 0.05€. When I edit the purchase, the correct price value will be displayed but I can not save my edits because the UI won't allow a price of 0.008226 per gram. I'd have to round the value to 0.01€

**kg:**
I can not enter 0.186 kg as a purchase as the UI expects the amount to be rounded to two digits. Rounding the value to 0.19 would work, but is quite a bit off from my actual purchase.

I'd actually would prefer the kg unit. The journal should display the purchase value as € / kg. What do you think?

**Comment by berrnd** [comment]
There are other issues about the rounding things. Currently all currency values are rounded to two digits. No rounding for amount values is enforced, but it seems that the `step` attribute also enforces then two digits for input validiation...

The price currently is related to the products **purchase** quantity unit (will be changed to be related to the products _stock_ quantity unit in the next version, as we had problems with that, of course this will be automatically done on purchase, so there it's still possible to just enter what you paid).

So if the digit restrication for amount values is removed, I think your problem should be solved.

**Comment by fusion44** [comment]
Thanks for the quick response - sounds good to me. 

I've just tried to add it on the master demo site and the input validation is still wrong. I'll try and tackle this, seems like a good first issue.

**Comment by fusion44** [comment]
I finally got my dev environment up and running. I've never used php before. If I had found https://github.com/grocy/grocy/pull/811 earlier, it'd have saved me at least one hour of trial end error.
